repos:
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.10.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://github.com/pycqa/flake8
    rev: 7.1.1
