# Auto generated by Vaimo API

# Rule 1/2
User-agent: Googlebot
Disallow: /nogooglebot/

# Rule 2/2
User-agent: *
Disallow: /*?
Disallow: /app/
Disallow: /bin/
Disallow: /catalog/category/view/
Disallow: /catalog/product_compare/
Disallow: /catalog/product/view/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /customer/
Disallow: /customer/account/
Disallow: /customer/account/login/
Disallow: /dev/
Disallow: /directory/
Disallow: /enable-cookies/
Disallow: /index.php/
Disallow: /js/
Disallow: /lib/
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /onestepcheckout/
Disallow: /*.php$
Disallow: /phpserver/
Disallow: /review/product/
Disallow: /sendfriend/
Disallow: /skin/
Disallow: /wishlist/

Sitemap: https://hlj.com/sitemap.xml
